/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda.gui;

/**
 *
 * @author Manu
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anadirReunionP = new javax.swing.JPopupMenu();
        popUp = new javax.swing.JFrame();
        DisplayType = new javax.swing.JTabbedPane();
        calendarFrame1 = new agenda.gui.calendarFrame();
        bookFrame1 = new agenda.gui.bookFrame();
        MenuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        exitSubmenu = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        agregarReunion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        anadirReunionP.getAccessibleContext().setAccessibleParent(jMenuItem3);

        javax.swing.GroupLayout popUpLayout = new javax.swing.GroupLayout(popUp.getContentPane());
        popUp.getContentPane().setLayout(popUpLayout);
        popUpLayout.setHorizontalGroup(
            popUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        popUpLayout.setVerticalGroup(
            popUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda PUCV");

        DisplayType.addTab("Calendar", calendarFrame1);

        javax.swing.GroupLayout bookFrame1Layout = new javax.swing.GroupLayout(bookFrame1);
        bookFrame1.setLayout(bookFrame1Layout);
        bookFrame1Layout.setHorizontalGroup(
            bookFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        bookFrame1Layout.setVerticalGroup(
            bookFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        DisplayType.addTab("Book", bookFrame1);

        file.setText("File");
        file.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                fileMenuSelected(evt);
            }
        });

        exitSubmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitSubmenu.setText("exit");
        exitSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSubmenuActionPerformed(evt);
            }
        });
        file.add(exitSubmenu);

        MenuBar.add(file);

        edit.setText("Edit");

        agregarReunion.setText("Añadir Reunión");
        agregarReunion.setComponentPopupMenu(anadirReunionP);
        agregarReunion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                agregarReunionComponentAdded(evt);
            }
        });
        agregarReunion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                agregarReunionComponentShown(evt);
            }
        });
        edit.add(agregarReunion);

        jMenuItem2.setText("Quitar Reunión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        edit.add(jMenuItem2);

        jMenuItem3.setText("Buscar Reunión");
        edit.add(jMenuItem3);

        jMenu3.setText("jMenu3");
        jMenu3.add(jSeparator1);

        edit.add(jMenu3);

        MenuBar.add(edit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayType, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayType)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_fileMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuSelected

    private void exitSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSubmenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitSubmenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void agregarReunionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_agregarReunionComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarReunionComponentShown

    private void agregarReunionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_agregarReunionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarReunionComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane DisplayType;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem agregarReunion;
    private javax.swing.JPopupMenu anadirReunionP;
    private agenda.gui.bookFrame bookFrame1;
    private agenda.gui.calendarFrame calendarFrame1;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem exitSubmenu;
    private javax.swing.JMenu file;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JFrame popUp;
    // End of variables declaration//GEN-END:variables
}
